---
title: "nyc"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(janitor)
library(skimr)
library(infer)
library(readxl)
library(stringr)
library(tidyr)
library(patchwork)
library(gt)
library(tidymodels)
library(knitr)
library(stargazer)
library(plm)
library(lmtest)
library(extrafont)
library(devtools)
library(ggplot2)

```

```{r Read in SCHMA and addon files along with list of replacement and replaced schools, include = FALSE}
# Read in main data set

data <- read.csv("raw/schma19962016.csv") %>% 
  clean_names()

addon <- read_csv("raw/stchso20052016.csv") %>% 
  clean_names()

#Load in collected data about new and failing schools
old_new_schools <- read_excel("raw/oldnewssc.xlsx")

# Create a list of schools so that I can see how they are named in this data

schools <- data %>% 
  select(schnam) %>% 
  distinct(schnam) %>% 
  arrange(schnam)

# Create a list of NYC's specialized schools

selective_schools <- c("BRONX HIGH SCHOOL OF SCIENCE", "BROOKLYN TECHNICAL HIGH SCHOOL", "STATEN ISLAND TECHNICAL HS", "STUYVESANT HIGH SCHOOL", "BROOKLYN LATIN, THE", "QUEENS HIGH SCHOOL FOR THE SCIENCES AT YORK COLLEG", "HIGH SCHOOL FOR MATHEMATICS, SCIENCE AND ENGINEERI", "HIGH SCHOOL OF AMERICAN STUDIES AT LEHMAN COLLEGE")

# Create a dataset that filters out observations for selective schools

data_selective_schools <- data %>% 
  filter(schnam %in% selective_schools)

```

```{r Load in and clean enrollment data 2006-2015, include = FALSE}

#Load in 2006-2012 and filter for high schools
#Schoolyear was in 20xx20xx format, so I deleted first four digits
#Had to convert to character form to do that
#Filtered for grades 9-12 that were not NA count

demo_20062012 <- read_csv("raw/enrollmentdata/2006_-_2012_School_Demographics_and_Accountability_Snapshot.csv") %>% 
  clean_names() %>% 
  mutate(schoolyear = as.character(schoolyear),
         schoolyear = gsub('^.{4}', '', schoolyear),
         schoolyear = as.numeric(schoolyear)) %>% 
  filter(!is.na(grade9) & !is.na(grade10) & !is.na(grade11) &!is.na(grade12)) %>% 
  mutate(total_hs_enrollment = grade9 + grade10 + grade11 + grade12)

#Load in 2011-2016 and filter for high schools
#Schoolyear was in 20xx-xx format so got rid of middle "x-x"
#Filtered for grades 9-12 that were not 0 count
#Coerce all character columns into numeric (get rid of '%' first)
demo_20112016 <- read_csv("raw/enrollmentdata/2011_-_2016_Demographic_Snapshot.csv") %>% 
  clean_names() %>% 
  mutate(year = str_replace(year, pattern = "\\d[:punct:]\\d", replacement = ""),
         year = as.numeric(year)) %>% 
  filter(grade_9 != 0 & grade_10 != 0 & grade_11 != 0 & grade_12 != 0) %>% 
  mutate(total_hs_enrollment = grade_9 + grade_10 + grade_11 + grade_12,
         percent_asian = as.numeric(sub("%", "", percent_asian)),
         percent_hispanic = as.numeric(sub("%", "", percent_hispanic)),
         percent_black = as.numeric(sub("%", "", percent_black)),
         percent_white = as.numeric(sub("%", "", percent_white)),
         percent_female = as.numeric(sub("%", "", percent_female)),
         percent_male = as.numeric(sub("%", "", percent_male)),
         percent_other = as.numeric(sub("%", "", percent_other)),
         percent_english_language_learners = as.numeric(sub("%", "", percent_english_language_learners)),
         percent_poverty = as.numeric(sub("%", "", percent_poverty)),
         percent_students_with_disabilities = as.numeric(sub("%", "", percent_students_with_disabilities))
         ) 

#Combined both data sets and combineed overlapping columns 
#Demographic data per school from 2006-2016
#Include only high school #s
demo_20062016 <- demo_20062012 %>% 
  filter(schoolyear != 2012) %>% 
  full_join(demo_20112016, by = c("dbn", 
                                  "schoolyear" = "year",
                                  "total_enrollment",
                                  "total_hs_enrollment",
                                  "prek" = "grade_pk",
                                  "k"= "grade_k",
                                  
                                  # For some reason, grade1 was cl
                                  
                                  "grad_e1" = "grade_1",
                                  "grade2" = "grade_2",
                                  "grade3" = "grade_3",
                                  "grade4" = "grade_4",
                                  "grade5" = "grade_5",
                                  "grade6" = "grade_6",
                                  "grade7" = "grade_7",
                                  "grade8" = "grade_8",
                                  "grade9" = "grade_9",
                                  "grade10" = "grade_10",
                                  "grade11" = "grade_11",
                                  "grade12" = "grade_12",
                                  "name" = "school_name",
                                  "asian_num" = "number_asian",
                                  "asian_per" = "percent_asian",
                                  "black_num" = "number_black",
                                  "black_per" = "percent_black", 
                                  "hispanic_num" = "number_hispanic",
                                  "hispanic_per" = "percent_hispanic", 
                                  "white_num" = "number_white",
                                  "white_per"= "percent_white",
                                  "female_num" = "number_female",
                                  "male_num" = "number_female",
                                  "ell_num" = "number_english_language_learners",
                                  "ell_percent" = "percent_english_language_learners",
                                  "frl_percent" = "percent_poverty"
                                  )) %>% 
  mutate(fl_or_frl_lunch = coalesce(frl_percent, fl_percent)) %>% 
  select(-prek, -k, -grad_e1, -grade2, -grade3, -grade4, -grade5, -grade6, -grade7, -grade8) %>% 
  arrange(dbn, schoolyear) 


# Commented code for loading in 2013-2018 data
#demo_20132018 <- read_csv("raw/enrollmentdata/2013_-_2018_Demographic_Snapshot_School.csv") %>% 
#  clean_names() %>% 
#  mutate(year = str_replace(year, pattern = "\\d[:punct:]\\d", replacement = ""),
#         year = as.numeric(year)) %>% 
# filter(grade_9 != 0 & grade_10 != 0 & grade_11 != 0 & grade_12 != 0) %>% 
#  mutate(total_hs_enrollment = grade_9 + grade_10 + grade_11 + grade_12)

#demo_20132018 

```

```{r Graduation Rates Cutoff Comparison, include = FALSE}

# Filter for high schools (defined as schools serving 9-12 at least)  

data_hs <- data %>% 
  filter(enrnumg12 != 0 & enrnumg11 != 0 & enrnumg10  != 0 & enrnumg09 != 0 ) %>% 
  group_by(year) %>% 
  mutate(percent_rank = percent_rank(hsopcthsgtot))

# Plot all schools by year and graduation rates

data_hs %>% 
  filter(hsopcthsgtot != is.na(hsopcthsgtot)) %>% 
  select(schnam, year, hsopcthsgtot) %>% 
  ggplot(aes(x = year, y = hsopcthsgtot, color = schnam)) + 
  geom_jitter() +
  theme(legend.position = "none")

# Plot percentile rank of school over time

data_hs %>% 
  filter(schnam %in% selective_schools) %>% 
  ggplot(aes(x= year, y = percent_rank, color = schnam)) +
  geom_line() +
  theme(legend.position = "none")

# Find out valid observations of graduation rates per year

data %>% 
  group_by(year) %>% 
  filter(hsopctdchtot != is.na(hsopcthsgtot)) %>% 
  select(schnam, year, hsopcthsgtot) %>% 
  count()

```

```{r grad_rates_clean (From grad rates 2005-2010), include = FALSE}
#Load in 2005-15 graduation rate data and clean variable names
grad_rates_20052015 <- read_excel("raw/graduationrates/2005-2015_Graduation_Rates_Public_School.xlsx") %>% 
  clean_names() 

# Clean the data so that it only contains observations of graduation classes for 4 Year August (or 4 Year June if August is not available)
grad_rates_clean <- grad_rates_20052015 %>% 
  filter(str_detect(cohort_category,"4 Year"), 
         demographic == "English Language Proficient") %>% 
  mutate(grad_year = cohort_year + 4)

grad_rates_clean$cohort_category <- factor(grad_rates_clean$cohort_category, levels = c("4 Year August", "4 Year  June"))

grad_rates_clean <- grad_rates_clean[order(grad_rates_clean$cohort_category),]

grad_rates_clean <- grad_rates_clean[!duplicated(grad_rates_clean[,c('dbn', 'cohort_year')]),]


grad_rates_clean <- grad_rates_clean %>% 
  group_by(dbn) %>% 
  arrange(cohort_year, .by_group = TRUE)

# Filter only for non "s" values of graduation percentage
# Turn Graduation percentage from chr to dbl
grad_rates_clean <- grad_rates_clean %>% 
  filter(total_grads_percent_of_cohort != "s") %>% 
  mutate(total_grads_percent_of_cohort = as.double(total_grads_percent_of_cohort),
         total_regents_percent_of_cohort = as.double(total_regents_percent_of_cohort),
         total_regents_percent_of_grads = as.double(total_regents_percent_of_grads),
         advanced_regents_percent_of_cohort = as.double(advanced_regents_percent_of_cohort),
         advanced_regents_percent_of_grads = as.double(advanced_regents_percent_of_grads))
  

# Plot 
# Must manually get rid of y labels and ticks or else it looks terrible

grad_rates_clean %>% 
  select(dbn, cohort_year, total_grads_percent_of_cohort) %>% 
  filter(total_grads_percent_of_cohort != "s") %>% 
  ggplot(aes(x = cohort_year, y = total_grads_percent_of_cohort, color = dbn)) +
  geom_point() +
  theme_classic() + 
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```

```{r Join both data sets (SCHMA + grad-rates2005-2010 + demo2006-2016), include = FALSE}

# Join the three data sets
# Because demo2006-2016 is missing 2005 data. I pulled those numbers from SCHMA
# demo2006-2016 has more reliable data, excpt for 2005

data_join <- data_hs %>% 
  full_join(grad_rates_clean, by = c("dbn", "year" = "grad_year")) %>% 
  full_join(demo_20062016, by = c("dbn", "year" = "schoolyear")) %>% 
  mutate(total_hs_enrollment_schnam = enrnumg09 + enrnumg10 + enrnumg11 + enrnumg12) %>% 
  mutate(total_hs_enrollment = coalesce(total_hs_enrollment, as.double(total_hs_enrollment_schnam)))

# tool to test commands
#data_join %>% 
 # select(dbn, schnam, year, total_hs_enrollment, total_hs_enrollment_schnam) %>% 
 # arrange(dbn, year) %>% 
 # mutate(total_hs_enrollment = coalesce(total_hs_enrollment, as.double(total_hs_enrollment_schnam)))
```

```{r 2005 Replaced and Replacement Schools, include = FALSE}

# Pull a list of the large failing schools that housed new replacement schools

large_failing_schools <- old_new_schools %>% 
  select(old_dbn, old_schnam, last_old_year) %>% 
  distinct() %>% 
  pull(old_dbn)

# Pull a list of the small replacement schools 
replacement_schools <- old_new_schools %>% 
  filter(!is.na(old_schnam) ) %>% 
  select(new_dbn, new_schnam, first_year_end) %>% 
  pull(new_dbn)

# Plot graduation rates of large failing schools that were closed

data_hs %>% 
  filter(dbn %in% large_failing_schools) %>% 
  select(dbn,hsopcthsgtot) %>% 
  arrange(dbn) %>% 
  ggplot(aes(x = year, y = hsopcthsgtot, color = dbn)) +
  geom_line()

# Plot graduation rates of new repalcement schools

data_hs %>% 
  filter(dbn %in% replacement_schools) %>% 
  ggplot(aes(x = year, y = hsopcthsgtot, color = dbn)) +
  geom_line()

#Join the old new schools data table to the clean grad rates so I can see the
#stats of all new schools and identified by old high school
grad_rates_clean_append <- grad_rates_clean %>% 
  filter(dbn %in% replacement_schools) %>% 
  left_join(old_new_schools, by = c("dbn" = "new_dbn")) %>% 
  filter(!is.na(old_dbn))


# Plot average graduation rates of new replacement schools organized by their former
# large school
grad_rates_clean_append %>% 
  group_by(old_dbn, cohort_year) %>% 
  summarize(mean_new_dbn = mean(total_grads_percent_of_cohort)) %>% 
  ggplot(aes(x = cohort_year + 4, y = mean_new_dbn, color = old_dbn)) +
  geom_line()

# Plot graduation rates of new replacements schools 

grad_rates_clean %>% 
  filter(dbn %in% old_new_schools$new_dbn) %>% 
  ggplot(aes(x = cohort_year + 4, y = total_grads_percent_of_cohort, color = dbn)) + 
  geom_line() +
  theme(legend.position = "none")
  

```

```{r Find comparable schools that werent closed, echo = FALSE}
# Explore data: Compare graduation metrics between the two data sets, organized by school across years
# Seems like total_grads_percent_of_cohort is more in line with hsopcthsgnyc
# Almost all schools have observations from 2005- we'll use that as a starting point
  
graduation_rates_failing_closed_joined <- data_join %>% 
  filter(dbn %in% old_new_schools$old_dbn) %>% 
  select(dbn, school, year, total_grads_percent_of_cohort, hsopcthsgtot) %>% 
  group_by(dbn) %>% 
  nest()

#Find graduation rates of schools in the middle 80th percentile (excluded tail ends to exclude outliers)

close_school_2005_graduation_rates <- data_join %>% 
  filter(year == 2005, 
         dbn %in% old_new_schools$old_dbn) %>% 
  select(dbn, schnam, school, total_grads_percent_of_cohort,hsopcthsgtot, hsopcthsgnyc) %>% 
  summarize(percentile_10 = quantile(as.numeric(total_grads_percent_of_cohort), 
                                     probs = 0.1, 
                                     na.rm = TRUE),
            percentile_90 = quantile(as.numeric(total_grads_percent_of_cohort),
                                     probs = 0.9, 
                                     na.rm = TRUE),
            percentile_50 = quantile(as.numeric(total_grads_percent_of_cohort),
                                     probs = 0.5, 
                                     na.rm = TRUE))

closed_10_grad <- close_school_2005_graduation_rates %>% 
  pull(percentile_10)

closed_50_grad <- close_school_2005_graduation_rates %>% 
  pull(percentile_50)

closed_90_grad <- close_school_2005_graduation_rates %>% 
  pull(percentile_90)

# 10th percentile :0.2389633206
# 50th percentile: 0.3885992
# 90th percentile: 0.46599

data_failing_open <- data_join %>% 
  
  #select only necessay information (faster processing)
  select(dbn, school, year, total_grads_percent_of_cohort, total_hs_enrollment, lcgschtyp) %>% 
  
  #exclude NAs and schools that were either replaced or were replacements in '05
  filter(!is.na(total_grads_percent_of_cohort),
         !dbn %in% old_new_schools$old_dbn &
         !dbn %in% old_new_schools$new_dbn) %>% 
  group_by(dbn) %>% 
  nest() %>% 
  
  #create column that indicates if there is data from 05-15
  mutate("avail20052015" = map_lgl(data, ~ifelse(2015 %in% .[[2]] & 2005 %in% .[[2]], 
                        TRUE,
                        FALSE))) %>% 
  
  # Create column that indicates it there is data from 2005
  mutate("avail2005" = map_lgl(data, ~ifelse(2005 %in% .[[2]], 
                        TRUE,
                        FALSE))) %>% 
  
  mutate("avail2015" = map_lgl(data, ~ifelse(2015 %in% .[[2]], 
                        TRUE,
                        FALSE))) %>% 
  
  # Filter for schools where there is available data from 2005
  filter(avail2005  == TRUE) %>% 
  
  # Create new column that indicates the graduation rate of school in 2005 
  mutate("grad_2005" = map_dbl(data, ~filter(., year == 2005) %>%           pull(total_grads_percent_of_cohort)),
         
         # Create column indicating if 2005 graduation rate falls in the failing schools closed middle 80th percentile
         "grad_rates_fail" = ifelse(grad_2005 <= closed_90_grad &
                                    grad_2005 >= closed_10_grad,
                                    TRUE,
                                    FALSE),
         
         "enrollment_2005" = map_dbl(data, ~filter(., year == 2005) %>%           pull(total_hs_enrollment))) %>% 
  # Filter for schools where graduation rates falls in the failing schools closed middle 80th percentile
  filter(grad_rates_fail == TRUE) %>% 
  arrange(enrollment_2005)


# Pull the dbn for all of these

failing_2005_list <- data_failing_open %>% 
  pull(dbn)
  
```

```{r Visualizing change in new york city high school sizes, echo = FALSE}

# All public school data

# Plot Number of high schools by enrollment
data_join %>% 
  unnest() %>% 
  ungroup(year) %>% 
  filter(year == 2015 |
         year == 2008 |
         year == 2007 |
         year == 2005 ) %>% 
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(x = total_hs_enrollment, fill = fct_rev(year))) +
  geom_histogram(alpha= 0.5, position = "identity", color = "black") +
  facet_wrap(~year) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(title = "Number of High Schools by HS Enrollment 2005, 2007, 2008, 2015",
       y = "# High Schools",
       x = "Total High School Enrollment")

# Plot distribution of high schools by enrollment
# Problem is that the distributions are % of the TOTAL number of high schools across time, not just of that year

data_join %>% 
  unnest() %>% 
  ungroup(year) %>% 
  filter(year == 2015 |
         year == 2008 |
         year == 2007 |
         year == 2005 ) %>% 
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(x = total_hs_enrollment, fill = fct_rev(year))) +
  geom_density(alpha= 0.5, color = "black") +
  facet_wrap(~year) +
  theme_classic() +
  theme(legend.title = element_blank()) +
  labs(title = "Distribution of High Schools by Enrollment '05, '07, '08, '15",
       y = "% of Total High Schools",
       x = "Total High School Enrollment")

# Plot number of high schools with enrollment less than 600 from 2000-2015

data_join %>% 
  unnest() %>% 
  # ungroup(year) %>% 
  filter(total_hs_enrollment <= 600,
         year >= 2000) %>% 
  count() %>% 
  ggplot(aes(x = year, y = n)) +
  geom_col()+ 
  labs(title = "Number of High Schools with Enrollment ≤ 600 from 2005-2015") +
  scale_y_continuous(name = "# High Schools",
                     limits = c(0, 500)) +
  scale_x_continuous(name = "School Year (As of June)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0, face = "bold"),
        plot.title.position = "plot",
        plot.subtitle = element_text(hjust = 0),
        text = element_text(family = "Times New Roman"))


```

```{r Small Failing Closed Open in 2005, include = FALSE}

# Set 600 as the arbitrary size for "small" schools
# Time permitting, perhaps taking the average of the 2005 replacement schools

data_failing_2005_small <- data_failing_open %>% 
  filter(enrollment_2005 <= 600 | is.na(enrollment_2005)) %>% 
  unnest() 
  
data_failing_2005_small_list <- data_failing_2005_small %>% 
  group_by(dbn) %>% 
  nest() %>% 
  pull(dbn)

data_failing_2005_small

```

```{r Large Failing Open in 2005, include = FALSE}

# Filter for all large schools that were open in 2005
failing_2005_large_list <- data_failing_open %>% 
  filter(enrollment_2005 > 600) %>% 
  pull(dbn)

## Failing Large Schools in 2005 that were open and eventually closed
# Data 
failing_2005_large_closed <- data_failing_open %>% 
  filter(enrollment_2005 > 600) %>% 
  filter(avail2015 == FALSE) %>% 
  unnest()

# dbn pull
failing_2005_large_closed_list <- data_failing_open %>% 
  filter(enrollment_2005 > 600) %>% 
  filter(avail2015 == FALSE) %>% 
  pull(dbn)
  

# Data for failing large schools in 2005 that were and are still open but shrank
# Data 
failing_2005_large_open_shrank <- data_failing_open %>% 
  filter(avail2015 == TRUE) %>%
  mutate("enrollment_2015" = map_dbl(data, ~filter(., year == 2015) %>%           pull(total_hs_enrollment))) %>% 
  filter(enrollment_2005 > 600) %>% 
  filter(enrollment_2015 <= 600 | enrollment_2015 <= enrollment_2005/2) %>% 
  unnest()

# dbn pull
failing_2005_large_open_shrank_list <- failing_2005_large_open_shrank %>% 
  group_by(dbn) %>% 
  nest() %>% 
  pull(dbn)


# Data for failing large schools in 2005 that are still open and maintain size
# Data
failing_2005_large_open_2015 <- data_failing_open %>% 
  filter(avail2015 == TRUE) %>%
  mutate("enrollment_2015" = map_dbl(data, ~filter(., year == 2015) %>%           pull(total_hs_enrollment))) %>% 
  filter(enrollment_2005 > 600) %>% 
  filter(enrollment_2015 >= 600 & enrollment_2015 >= enrollment_2005/2) %>% 
  unnest()

# dbn pull
failing_2005_large_open_2015_list <- failing_2005_large_open_2015 %>% 
  group_by(dbn) %>% 
  nest() %>% 
  pull(dbn)

```

```{r Compare closed, replacement schools with Large Failing Open Schools in 2005 , echo = TRUE}

## Data for all large schools (>600) schools with graduation rates in the middle
## 80th percentile
## not yet announced for closure as of November 2005
replacement_schools_vs_all_failing <- data_join %>% 
  filter(dbn %in% replacement_schools |
         dbn %in% large_failing_schools |
         dbn %in% failing_2005_large_list) %>% 
  select(dbn, year, total_grads_percent_of_cohort) %>% 
  arrange(dbn, year) %>% 
  mutate(data_cat = ifelse(dbn %in% large_failing_schools,
                           "Announced for Closure in 2005",
                              ifelse(dbn %in% replacement_schools,
                               "Small Replacement Schools opened by 2005",
                               "Failing Open Schools in 2005"))) %>% 
  # Picked 2008 as an arbitrary date, just to show what graduation rates were like 
  # for schools that were closed
  filter(!dbn %in% large_failing_schools | year <= 2008) %>% 
  
  # Started at '06 because 2005 had a small sample size of all the schools
  # Data was also kinda wonky but not sure if that's a good reason for excluding
  filter(!dbn %in% replacement_schools | year >= 2006)


# Plot average graduation rates of schools from 2005-2015, subsetted into:
# 1) Closed failing schools 2) Small Replacement Schools 3) Open failing schools
replacement_schools_vs_all_failing %>% 
  group_by(year, data_cat) %>% 
  summarize(avg_grad = mean(total_grads_percent_of_cohort, na.rm =TRUE)) %>% 
  ggplot(aes(x = year, y = avg_grad, color = data_cat)) +
  geom_point() +
  geom_line() +
  labs(title = "Average Graduation Rates from 2005-2015",
       y = "Average Graduation Rate",
       x = "School Year as of June",
       caption ="Values for the treated group in 2006 was omitted due to too few observations \n Values for the 'To Close' group was omitted after 2008 due to too few observations") +
  scale_color_discrete(name = "", 
                       labels = c("To Close (2005)", 
                                  "Control", 
                                  "Treated Schools"),
                       guide = guide_legend(reverse = TRUE)) +
   scale_x_continuous(limits = c(2005, 2015), breaks = c(2005, 2010, 2015)) +
   scale_y_continuous(limits = c(0.3, 0.8)) +
   theme_classic() +
   theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0.5, face = "italic"))


# Create a table displaying average graduation rates from 05-15, for each school type
replacement_schools_vs_all_failing %>% 
  group_by(year, data_cat) %>% 
  summarize(avg_grad = mean(total_grads_percent_of_cohort, na.rm =TRUE)) %>% 
  pivot_wider(names_from = data_cat, values_from = avg_grad) %>% 
  filter(year > 2004 & year < 2016) %>% 
  select(year, "Failing Open Schools in 2005", "Small Replacement Schools opened by 2005", "Announced for Closure in 2005") %>% 
  ungroup(year, data_cat)  %>% 
  gt() %>% 
  tab_header(title = "Average Graduation Rates from 2005-2015") %>% 
  tab_spanner(label = "Graduation Rates", columns = 2:4) %>% 
  cols_label( "year" = "School Year (As of June)",
              "Failing Open Schools in 2005" = "Control Group",
              "Announced for Closure in 2005" = "To Close (2005)",
              "Small Replacement Schools opened by 2005" = "Small Replacement") %>% 
  cols_align(align = "center", columns = 1:4) %>% 
  fmt_number(columns = 2:4, decimals = 2) 

```

```{r Compare Replacement Schools with Large Failing Open Schools in 2005 sorted by large failing open schools outcomes, echo = FALSE}
# Plot a line graph showing the relationship between year and graduation rates
# per type of school

replacement_schools_grad_vs_failing <- data_join %>% 
  filter(dbn %in% replacement_schools |
         dbn %in% large_failing_schools |
         dbn %in% failing_2005_large_open_shrank_list |
         dbn %in% failing_2005_large_closed_list |
         dbn %in% failing_2005_large_open_2015_list) %>% 
  
  # Did this to see if there was any pre-2005 data on large failing schools but seems like there isn't
  #mutate(total_grads_percent_of_cohort = coalesce(total_grads_percent_of_cohort, hsopcthsgnyc/100)) %>% 
  select(dbn, year, total_grads_percent_of_cohort, total_hs_enrollment) %>% 
  arrange(dbn, year) %>% 
  mutate(data_cat = ifelse(dbn %in% large_failing_schools,
                           "Announced for Closure in 2005",
                              ifelse(dbn %in% replacement_schools,
                               "Small Replacement Schools opened by 2005",
                                 ifelse(dbn %in% failing_2005_large_closed_list,
                                      "Large Eventually Closed",
                                      ifelse(dbn %in% failing_2005_large_open_shrank_list,
                                             "Large and Shrank",
                                             "Large and Operating"))))) %>% 
  
  # Picked 2008 as an arbitrary date, just to show what graduation rates were like 
  # for schools that were closed
  filter(!dbn %in% large_failing_schools | year <= 2008) %>% 
  
  # Started at '06 because 2005 had a small sample size of all the schools
  # Data was also kinda wonky but not sure if that's a good reason for excluding
  filter(!dbn %in% replacement_schools | year >= 2006)

# Plot it
replacement_schools_grad_vs_failing %>% 
  ggplot(aes(x = year, y = total_grads_percent_of_cohort, color = data_cat)) +
  geom_smooth(method = "lm",  se = FALSE)

# Plot that average graduation rates by category across years
replacement_schools_grad_vs_failing %>% 
  group_by(year, data_cat) %>% 
  summarize(avg_grad = mean(total_grads_percent_of_cohort, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = avg_grad, color = data_cat)) +
  geom_point() +
  geom_line() +
  labs(title = "Average Graduation Rates from 2005-2015",
       y = "Average Graduation Rate",
       x = "School Year as of June") +
  scale_color_discrete(name = "",
                       breaks = c("Small Replacement Schools opened by 2005",
                                  "Announced for Closure in 2005",
                                  "Large and Operating",
                                  "Large and Shrank",
                                  "Large Eventually Closed"), 
                       labels = c("Treatment", 
                                  "To Close (2005)", 
                                  "Control: Open",
                                  "Control: Shrank",
                                  "Control: Closed")) +
   scale_x_continuous(limits = c(2005, 2015), breaks = c(2005, 2010, 2015)) +
   scale_y_continuous(limits = c(0.3, 0.8)) +
   theme_classic()

# Create a table displaying average graduation rates from 05-15, for each school type
replacement_schools_grad_vs_failing %>% 
  group_by(year, data_cat) %>% 
  summarize(avg_grad = mean(total_grads_percent_of_cohort, na.rm =TRUE)) %>% 
  pivot_wider(names_from = data_cat, values_from = avg_grad) %>% 
  filter(year > 2004 & year < 2016) %>% 
  select(year, 
         "Large and Operating",
         "Large and Shrank",
         "Large Eventually Closed",
         "Small Replacement Schools opened by 2005",
         "Announced for Closure in 2005") %>% 
  ungroup(year, data_cat)  %>% 
  gt() %>% 
  tab_header(title = "Average Graduation Rates from 2005-2015") %>% 
  tab_spanner(label = "Control", columns = 2:4) %>% 
  cols_label(year = "School Year (As of June)", 
             "Large and Operating" = "Open",
             "Large and Shrank" = "Shrank",
             "Large Eventually Closed" = "Closed",
             "Small Replacement Schools opened by 2005" = "Treatment",
              "Announced for Closure in 2005" = "To Close (2005)") %>% 
  cols_align(align = "center", columns = 1:6) %>% 
  fmt_number(columns = 2:6, decimals = 2) 

replacement_schools_grad_vs_failing %>% 
  filter(data_cat == "Small Replacement Schools opened by 2005",
         year != 2016)
```

```{r Enrollment numbers by school category, echo = FALSE}
# Plot average enrollment sizes by category across years
replacement_schools_grad_vs_failing %>% 
  group_by(year, data_cat) %>% 
  summarize(avg_hs_enrollment = mean(total_hs_enrollment, na.rm =TRUE)) %>% 
  ggplot(aes(x = year, y = avg_hs_enrollment, color = data_cat)) +
  geom_point() +
  geom_line() +
  labs(title = "Average HS Enrollment from 2005-2015",
       y = "Average HS Enrollment",
       x = "School Year as of June") +
  scale_color_discrete(name = "",
                       breaks = c("Small Replacement Schools opened by 2005",
                                  "Announced for Closure in 2005",
                                  "Large and Operating",
                                  "Large and Shrank",
                                  "Large Eventually Closed"), 
                       labels = c("Treated Schools", 
                                  "To Close (2005", 
                                  "Control: Open",
                                  "Control: Shrank",
                                  "Control: Closed")) +
   scale_x_continuous(limits = c(2005, 2015), breaks = c(2005, 2010, 2015)) +
   theme_classic() +
   theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))


data_join %>% 
  filter(dbn == "29Q272") %>% 
  select(dbn, school, total_grads_percent_of_cohort, hsonumcohtot, hsonumcohnyc, hsonumhsgtot)
```

```{r Compare Replacement Schools with Large Failing Open Schools in 2005 sorted by large failing open schools outcomes, echo = FALSE}
```

```{r Compare Graduation Quintiles, echo = FALSE}

# Create dataset that describes 20,50,80 percentiles of graduation per year
grad_rates_nest <- data_join %>% 
  select(dbn, year, total_grads_percent_of_cohort) %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(percentile_20 = map_dbl(data,  ~ quantile(.[[2]], probs = .2, na.rm = TRUE)),
         percentile_80 = map_dbl(data,  ~ quantile(.[[2]], probs = .8, na.rm = TRUE)),
         percentile_50 = map_dbl(data,  ~ quantile(.[[2]], probs = .5, na.rm = TRUE))) %>% 
  arrange(year) %>% 
  select(-data)

#Graph the median result with errorbars at 80 and 20
grad_rates_nest %>% 
  ggplot(aes(x = year, y = percentile_50)) +
  geom_point() +
  geom_errorbar(aes(ymin = percentile_20, ymax = percentile_80)) +
  labs(title = "Highschool Graduation Rates 2005-2015",
       subtitle = "20, 50, 80 Percentiles",
       y = "Graduation Rate",
       x = "School Year as of June") +
  scale_x_continuous(breaks = c(2005, 2010, 2015),
                     limits = c(2004, 2016)) +
  scale_y_continuous(limits = c(.3, 1)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0, face = "bold"),
        plot.title.position = "plot",
        plot.subtitle = element_text(hjust = 0),
        text = element_text(family = "Times New Roman"))

## Chart with changes in graduation rates from 2005-2015 incl. pp and per change
grad_rates_table <- grad_rates_nest %>% 
  filter(year == 2005 |
         year == 2015) %>% 
  pivot_longer(cols = starts_with("percentile_"), names_to = "percentile", values_to = "graduation_rate") %>% 
  pivot_wider(names_from = "year", values_from = "graduation_rate") %>% 
  mutate("percent_point_change" = ((.[[3]] - .[[2]])*100),
         "percent_change" = (.[[3]] - .[[2]])/.[[2]]*100,
         "percentile" = ifelse(percentile == "percentile_20", 
                               "20th",
                               ifelse(percentile == "percentile_80",
                                      "80th",
                                      "50th"))) %>% 
  arrange(desc(percentile)) %>% 
  gt() %>% 
  fmt_number(columns = 2:5) %>% 
  cols_label(percentile = "Percentile" ,
             percent_point_change = "PP",
             percent_change = "%") %>% 
  tab_spanner(label = "Graduation Rates", columns = 2:3) %>% 
  tab_spanner(label = "Change", columns = 4:5) %>% 
  tab_header(title= "High School Graduation Rates 2005-2015") %>% 
  cols_align(align = "center", columns = TRUE) %>% 
  
  # A clunky way of formatting all text to Times New Roman but couldn't find any 
  # other way within the gt package
  
  tab_style(style = cell_text(font = "Times New Roman"), 
            locations = list(cells_column_labels(columns = 1:5),
                          cells_body(), 
                          cells_title(), 
                          cells_column_spanners(spanners = c("Graduation Rates", 
                                                             "Change"))
                          ) 
            ) %>% 
  
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_title()) %>% 
  tab_options(table.width = px(650),
              heading.align = "left",
              heading.border.bottom.style = "hidden",
              heading.title.font.size = 16
              ) 

grad_rates_table %>% 
  gtsave("hs_grad_rates_overview.html", path = "~/Documents/EC 980B/final_project/nyc/tables")


```

```{r Compare Regent/Cohort Quintiles, echo = FALSE}
# Create dataset that describes 20,50,80 percentiles of regents/cohort per year
grad_rates_regents_cohort <- grad_rates_clean %>% 
  group_by(cohort_year) %>% 
  nest() %>% 
  mutate(percentile_20 = map_dbl(data,  ~ quantile(.[[9]], probs = .2)),
         percentile_80 = map_dbl(data,  ~ quantile(.[[9]], probs = .8)),
         percentile_50 = map_dbl(data,  ~ quantile(.[[9]], probs = .5)),
         year = cohort_year + 4) %>% 
  arrange(cohort_year) %>% 
  select(-data)

#Graph the median result with errorbars at 80 and 20
grad_rates_regents_cohort %>% 
  ggplot(aes(x = year, y = percentile_50)) +
  geom_point() +
  geom_errorbar(aes(ymin = percentile_20, ymax = percentile_80)) +
  labs(title = "Regent Diploma Rate per Cohort 2005-2015",
       subtitle = "20, 50, 80 Percentiles",
       y = "Regent Diploma Rate (Cohort)",
       x = "School Year as of June") +
  scale_x_continuous(breaks = c(2005, 2010, 2015),
                     limits = c(2004, 2016)) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0, face = "bold"),
        plot.title.position = "plot",
        plot.subtitle = element_text(hjust = 0),
        text = element_text(family = "Times New Roman"))
```

```{r Compare Regents per Graduates Quintiles, include = FALSE}
# Create dataset that describes 20,50,80 percentiles of regents/grads per year
grad_rates_regents_grads <- grad_rates_clean %>% 
  group_by(cohort_year) %>% 
  nest() %>% 
  mutate(percentile_20 = map_dbl(data,  ~ quantile(.[[10]], probs = .2, na.rm = TRUE)),
         percentile_80 = map_dbl(data,  ~ quantile(.[[10]], probs = .8, na.rm = TRUE)),
         percentile_50 = map_dbl(data,  ~ quantile(.[[10]], probs = .5, na.rm = TRUE)),
         year = cohort_year + 4) %>% 
  arrange(year) %>% 
  select(-data)

#Graph the median result with errorbars at 80 and 20
grad_rates_regents_grads %>% 
  ggplot(aes(x = year, y = percentile_50)) +
  geom_point() +
  geom_errorbar(aes(ymin = percentile_20, ymax = percentile_80)) +
  labs(title = "Regent Diploma Rate of Graduates 2005-2015",
       subtitle = "20, 50, 80 Percentiles",
       y = "Regent Diploma Rate (Graduates)",
       x = "School Year as of June") +
  scale_x_continuous(breaks = c(2005, 2010, 2015),
                     limits = c(2004, 2016)) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
```

```{r Compare AdvRegents/Cohort Quintiles, include = FALSE}
# Create dataset that describes 20,50,80 percentiles of adv regents/cohort
grad_rates_advregents_cohort <- grad_rates_clean %>% 
  group_by(cohort_year) %>% 
  nest() %>% 
  mutate(percentile_20 = map_dbl(data,  ~ quantile(.[[13]], probs = .2, na.rm = TRUE)),
         percentile_80 = map_dbl(data,  ~ quantile(.[[13]], probs = .8, na.rm = TRUE)),
         percentile_50 = map_dbl(data,  ~ quantile(.[[13]], probs = .5, na.rm = TRUE))) %>% 
  arrange(cohort_year) %>% 
  select(-data)

#Graph the median result with errorbars at 80 and 20
grad_rates_advregents_cohort %>% 
  ggplot(aes(x = cohort_year, y = percentile_50)) +
  geom_point() +
  geom_errorbar(aes(ymin = percentile_20, ymax = percentile_80))
```

```{r join data_join with 2005-2016 }

```

```{r Comparing Demographic Data of Closed Schools pre-05 and replacement schools post-05, echo = FALSE}

# Track pre-2006 demographic change sin schools that were annoucne for closure in 2005 using SCHMA data

demo_closed05_20002005_plot <- data_join %>% 
  filter(dbn %in% large_failing_schools) %>% 
  select(dbn, year, enrnumtot, enrnumasi, enrnumhis, enrnumafm, enrnumwht, enrnumoth) %>%
  mutate("per_asian" = enrnumasi/enrnumtot,
         "per_hispanic" = enrnumhis/enrnumtot,
         "per_black" = enrnumafm/enrnumtot,
         "per_white" = enrnumwht/enrnumtot) %>% 
  pivot_longer(cols = starts_with("per_"), names_to = "demographic", values_to = "percent") %>% 
  group_by(year, demographic) %>% 
  summarize(avg_per = mean(percent, na.rm = TRUE)) %>% 
  # Must use pivot longer on demo_per observations
  ggplot(aes(x = year, y = avg_per, shape = demographic)) +
  geom_line() +
  geom_point(aes(shape = demographic), size = 2) +
  scale_x_continuous(limits = c(2002,2005),
                     breaks = c(2002,2005)) +
  ylim(0, .6) +
  theme_classic() +
  labs(title = "Demographics of Pre + Post Treatment",
       subtitle = "Schools to Close",
       y = "Fraction of High School Enrollment",
       x = "School Year as of June") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0, face = "bold"),
        plot.title.position = "plot",
        plot.subtitle = element_text(hjust = 0.2),
        text = element_text(family = "Times New Roman"),
        axis.title.x = element_text(hjust = 1)) 

# Track racial demographic changes in replacement schools from 05-15
demo_replacement05_20062015_plot <- data_join %>% 
  filter(dbn %in% replacement_schools) %>% 
  select(dbn, year, asian_per, hispanic_per, black_per, white_per) %>% 
  pivot_longer(cols = ends_with("_per"), names_to = "demographic", values_to = "percent") %>% 
  group_by(year, demographic) %>% 
  summarize(avg_per = mean(percent/100, na.rm = TRUE)) %>% 
  # Must use pivot longer on demo_per observations
  ggplot(aes(x = year, y = avg_per, shape = demographic)) +
  geom_line() +
  geom_point(aes(shape = demographic), size = 2) +
  labs(subtitle = "Replacement Schools",
        x = "") +
  scale_x_continuous(limits = c(2006, 2009), breaks = c(2006, 2009)) +
  ylim(0, .6) +
  scale_shape_discrete(name = "Race", labels = c("Asian", "Black", "Hispanic", "White")) +
  theme_classic() +
  theme(axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(hjust = 0, face = "bold"),
        plot.title.position = "plot",
        plot.subtitle = element_text(hjust = 0),
        text = element_text(family = "Times New Roman"))

# Combine above two plots to compare school and repelacement schools 

demo_closed05_20002005_plot + demo_replacement05_20062015_plot
  



# Track racial demographic changes in schools that were announced for closure in 2005 using 2005-2015 demo data

data_join %>% 
  filter(dbn %in% large_failing_schools) %>% 
  select(dbn, year, asian_per, hispanic_per, black_per, white_per) %>% 
  pivot_longer(cols = ends_with("_per"), names_to = "demographic", values_to = "percent") %>% 
  group_by(year, demographic) %>% 
  summarize(avg_per = mean(percent, na.rm = TRUE)) %>% 
  # Must use pivot longer on demo_per observations
  ggplot(aes(x = year, y = avg_per, color = demographic)) +
  geom_line() +
  scale_x_continuous(limits = c(2005, 2015),
                     breaks = c(2005, 2010, 2015)) +
  theme_classic()



# Track racial demographic changes in 4 large failing schools still open at the same size

data_join %>% 
  filter(dbn %in% failing_2005_large_open_2015_list) %>% 
  select(dbn, year, asian_per, hispanic_per, black_per, white_per) %>% 
  pivot_longer(cols = ends_with("_per"), names_to = "demographic", values_to = "percent") %>% 
  group_by(year, demographic) %>% 
  summarize(avg_per = mean(percent, na.rm = TRUE)) %>% 
  # Must use pivot longer on demo_per observations
  ggplot(aes(x = year, y = avg_per, color = demographic)) +
  geom_line() +
  xlim(2005, 2015) +
  theme_classic() 
# Average enrollments have stayed the same, but what about concentrations per school?
# Current visualizations don't address the issue of segregation between schools.

```

```{r check free and reduced lunches, echo = FALSE}

frl <- data_join %>% 
  select(dbn, fl_or_frl_lunch) %>% 
  filter(year >= 2006) %>%
  filter(dbn %in% failing_2005_list) %>%
  group_by(year) %>% 
  nest() %>% 
  mutate(percentile_20 = map_dbl(data,  ~ quantile(.[[2]], probs = .2, na.rm = TRUE)),
         percentile_80 = map_dbl(data,  ~ quantile(.[[2]], probs = .8, na.rm = TRUE)),
         percentile_50 = map_dbl(data,  ~ quantile(.[[2]], probs = .5, na.rm = TRUE))) %>% 
  select(-data) %>% 
  ggplot(aes(x = year, y = percentile_50)) +
  geom_point() +
  geom_errorbar(aes(ymin = percentile_20, ymax = percentile_80)) 

frl

data_join %>% 
  select(year, dbn, ccdenrnumfrl) %>% 
  filter(year == 2005)


ppe <- data_join %>% 
  select(dbn, ppexpotps) %>% 
  filter(year >= 2005) %>%
  filter(dbn %in% failing_2005_list) %>%
  group_by(year) %>% 
  nest() %>% 
  mutate(percentile_20 = map_dbl(data,  ~ quantile(.[[2]], probs = .2, na.rm = TRUE)),
         percentile_80 = map_dbl(data,  ~ quantile(.[[2]], probs = .8, na.rm = TRUE)),
         percentile_50 = map_dbl(data,  ~ quantile(.[[2]], probs = .5, na.rm = TRUE))) %>% 
  select(-data) %>% 
  ggplot(aes(x = year, y = percentile_50)) +
  geom_point() +
  geom_errorbar(aes(ymin = percentile_20, ymax = percentile_80)) 


ppe


```

```{r Observe Data of graduation and enrollment, echo = FALSE}

# All Years
data_join %>% 
  ggplot(aes(x = total_hs_enrollment, y = total_grads_percent_of_cohort)) +
  geom_point() +
  geom_smooth(method = "lm")

# 2006
data_join %>% 
  subset(year == 2006) %>% 
  ggplot(aes(x = total_hs_enrollment, y = total_grads_percent_of_cohort)) +
  geom_point()

# 2010
data_join %>% 
  subset(year == 2010) %>% 
  ggplot(aes(x = total_hs_enrollment, y = total_grads_percent_of_cohort)) +
  geom_point()

# 2015
data_join %>% 
  subset(year == 2015) %>% 
  ggplot(aes(x = total_hs_enrollment, y = total_grads_percent_of_cohort)) +
  geom_point()

```

```{r OLS + Time Fixed Effects Regressions: Entire Population, echo = FALSE}

# Time fixed effects regression using plm()
regression_tfe <- data_join %>%
  ungroup(year) %>% 
  
  # Not enough observations pre 2006
  subset(year >= 2006) %>% 
  
  # Multiplied decimal fractions by 100 
  mutate(total_grads_percent_of_cohort = total_grads_percent_of_cohort *100,
         
         #Convert year into a factor
         year = as.factor(year)) %>% 
  plm(total_grads_percent_of_cohort ~ total_hs_enrollment + asian_per + black_per + hispanic_per + white_per + fl_or_frl_lunch, 
      data = .,
      index = "year",
      
      # Indicated a fixed effect regression
      model = "within")

# Check for Heteroskedasticity within the Time-Fixed Effects Model
# Reject Null Hypothesis of homoskedasticity
bptest(regression_tfe)

# Store robust standard errors into regression_tfe$robust  \\ Same as adding "r"
# at the end of regression in STATA
regression_tfe$robust <- coeftest(regression_tfe, vcovHC(regression_tfe, type = "HC1"))

# Plot time fixed effect regression
stargazer(regression_tfe,
          
          # Substitute in robust standard errors
          se = list(regression_tfe$robust[,2]),
          title = "Title",
          header = FALSE,
          dep.var.labels= "Graduation Rate (% of Grade 9 Cohort)",
          
          covariate.labels = c("Total HS Enrollment", 
                               "% Asian",
                               "% Black",
                               "% Hispanic", 
                               "% White",  
                               "% Free/Reduced Lunch"),
          digits = 4,
          out = "tables/table1.html")


## OLS Regression + Time Fixed Effects Regression 

# Create OLS Regression Model 
regression_ols <- data_join %>%
  ungroup(year) %>% 
  
  # Not enough observations pre-2006
  subset(year >= 2006) %>% 
  mutate(total_grads_percent_of_cohort = total_grads_percent_of_cohort *100,
         
         #Convert year into a factor
         year = as.factor(year)) %>% 
  plm(total_grads_percent_of_cohort ~ total_hs_enrollment + asian_per + black_per + hispanic_per + white_per + fl_or_frl_lunch, 
      data = ., 
      index = "year", 
      
      # Indicates OLS model regression
      model = "pooling")

# Calculate Robust standard errors \\ Same as adding "r" at the end of regression in STATA
regression_ols$robust <- coeftest(regression_ols, vcovHC(regression_ols, type = "HC1"))

# Plot into a table results of OLS vs. Time Fixed Effects
stargazer(regression_ols, regression_tfe,
          
          # Replaced standard errors with robust standard errors
          se = list(regression_ols$robust[,2], regression_tfe$robust[,2]),
          title = "Title",
          column.labels = c("OLS", "Time Fixed Effects"),
          
          dep.var.labels= "Graduation Rate (% of Grade 9 Cohort)",
          
          covariate.labels = c("Total HS Enrollment", 
                               "% Asian",
                               "% Black",
                               "% Hispanic", 
                               "% White",  
                               "% Free/Reduced Lunch"),
          digits = 4,
          out = "tables/table2.html")

```

```{r OLS + Time Fixed Effects Regressions: Experiment Population, echo = FALSE}


# Time fixed effects regression using plm()
regression_tfe_exp <- data_join %>%
  ungroup(year) %>% 
  
  # Not enough observations pre 2006
  subset(year >= 2006) %>% 
  
  # Filter for schools that are in the experiment population
  # Schools failing in 2005 but not closed
  filter(dbn %in% failing_2005_list | 
           
         # Schools failing in 2005 announced for closure 
         dbn %in% large_failing_schools |
           
          # Schools that would replace closed failed schools 
         dbn %in% replacement_schools) %>% 
  
  # Multiplied decimal fractions by 100 
  mutate(total_grads_percent_of_cohort = total_grads_percent_of_cohort *100,
         
         #Convert year into a factor
         year = as.factor(year)) %>% 
  plm(total_grads_percent_of_cohort ~ total_hs_enrollment + asian_per + black_per + hispanic_per + white_per + fl_or_frl_lunch, 
      data = .,
      index = "year",
      
      # Indicated a fixed effect regression
      model = "within")

# Check for Heteroskedasticity within the Time-Fixed Effects Model
# Reject Null Hypothesis of homoskedasticity
bptest(regression_tfe_exp)

# Store robust standard errors into regression_tfe$robust  \\ Same as adding "r"
# at the end of regression in STATA
regression_tfe_exp$robust <- coeftest(regression_tfe_exp, vcovHC(regression_tfe_exp, type = "HC1"))

# Plot time fixed effect regression
stargazer(regression_tfe_exp,
          
          # Substitute in robust standard errors
          se = list(regression_tfe_exp$robust[,2]),
          title = "Title",
          header = FALSE,
          dep.var.labels= "Graduation Rate (% of Grade 9 Cohort)",
          
          covariate.labels = c("Total HS Enrollment", 
                               "% Asian",
                               "% Black",
                               "% Hispanic", 
                               "% White",  
                               "% Free/Reduced Lunch"),
          digits = 4,
          out = "tables/table3.html")


## OLS Regression + Time Fixed Effects Regression 

# Create OLS Regression Model 
regression_ols_exp <- data_join %>%
  ungroup(year) %>% 
  
  # Not enough observations pre-2006
  subset(year >= 2006) %>% 
  
  # Filter for experiment population
  filter(dbn %in% failing_2005_list | 
         
       # Schools failing in 2005 announced for closure 
       dbn %in% large_failing_schools |
         
        # Schools that would replace closed failed schools 
       dbn %in% replacement_schools) %>% 
  
  mutate(total_grads_percent_of_cohort = total_grads_percent_of_cohort *100,
         
         #Convert year into a factor
         year = as.factor(year)) %>% 
  plm(total_grads_percent_of_cohort ~ total_hs_enrollment + asian_per + black_per + hispanic_per + white_per + fl_or_frl_lunch, 
      data = ., 
      index = "year", 
      
      # Indicates OLS model regression
      model = "pooling")

# Calculate Robust standard errors \\ Same as adding "r" at the end of regression in STATA
regression_ols_exp$robust <- coeftest(regression_ols_exp, vcovHC(regression_ols_exp, type = "HC1"))

# Plot into a table results of OLS vs. Time Fixed Effects
stargazer(regression_ols_exp, regression_tfe_exp,
          
          # Replaced standard errors with robust standard errors
          se = list(regression_ols_exp$robust[,2], regression_tfe_exp$robust[,2]),
          title = "Title",
          column.labels = c("OLS", "Time Fixed Effects"),
          
          dep.var.labels= "Graduation Rate (% of Grade 9 Cohort)",
          
          covariate.labels = c("Total HS Enrollment", 
                               "% Asian",
                               "% Black",
                               "% Hispanic", 
                               "% White",  
                               "% Free/Reduced Lunch"),
          digits = 4,
          out = "tables/table4.html")



```

```{r, echo = FALSE}
# Remove transfer schools from analysis?

data_join %>% 
  filter(dbn %in%  replacement_schools) %>% 
  filter(dbn == "02M565") %>% 
  # filter(lcgschtyp == "TRANSFER SCHOOL") %>% 
  select(schnam, dbn, year, lcgschtyp)

```








